### ISSUE TITLE
(result and rho) image

### ISSUE THREAD

**Issue by lovelyvivi** [liurui39660/SnnDpc#2]
Firstly,your idea is   innovative and efficient, but I don't understand that in the library, while depicting the result and rho images,  the  library displays a 3D image, but it is actually two-dimensional.sincerely, I want to know how to solve it . Hope to get your reply. And,would you mind telling me the source website of your  dataset ?

**Comment by liurui39660** [comment]
Hi, as I remember, those figures are produced by the old Matlab code. For that, you can simply click on the figure (or one of the sub-figure), then use the arrow key to control the rotation. 

For the dataset, you can download from <http://cs.joensuu.fi/sipu/datasets/>, under the "shape sets" category.
